### ISSUE TITLE
version conflicts

### ISSUE THREAD

**Issue by yunstanford** [toumorokoshi/uranium#31]
```
pip._vendor.pkg_resources.ContextualVersionConflict: (schematics 2.0.0a1 (/lib/python3.5/site-packages), Requirement.parse('schematics>=2.0.0'), {'transmute-core'})
```
why is it a version conflict ? `2.0.0a1 > 2.0.0`.

**Comment by toumorokoshi** [comment]
pep440 explains this pretty well, but 2.0.0a1 is a pre-release, meaning that it is ordered lower than 2.0.0.

https://www.python.org/dev/peps/pep-0440/#exclusive-ordered-comparison

in pep440, `2.0.0a1 < 2.0.0`
